# ci-android.yml
name: CI-android

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.22.6
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: patrick.raguin/Snake
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: BAM
          file: build/app/outputs/apk/release/app-release.apk
          notifyTesters: true
          debug: true
